name: Documentation Update
description: Suggest improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation", "good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!
        
        **Note for Copilot Coding Agent:** Documentation tasks are well-suited for AI agents when requirements are clear.

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What kind of documentation needs updating?
      options:
        - README.md
        - AGENTS.md
        - API Documentation
        - Architecture Documentation
        - Setup/Installation Guide
        - CI/CD Documentation
        - Code Comments/Docstrings
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What needs to be documented or updated?
      description: Describe what's missing, incorrect, or unclear
      placeholder: The installation instructions for... are unclear because...
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: Affected Documentation Files
      description: List the documentation files that need to be updated
      placeholder: |
        - README.md (add Docker installation steps)
        - docs/CI_CD_QUICK_START.md (fix outdated workflow names)
        - backend/app/services/fraud_service.py (add docstrings)
    validations:
      required: false

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Changes
      description: What changes should be made?
      placeholder: |
        Suggest adding:
        1. Prerequisites section
        2. Step-by-step Docker setup
        3. Troubleshooting common errors
    validations:
      required: false

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What makes this documentation update complete?
      options:
        - label: Documentation is clear and accurate
          required: true
        - label: Examples provided (if applicable)
        - label: Links to related documentation included
        - label: Spelling and grammar checked
        - label: Code snippets tested and working
        - label: Screenshots/diagrams updated (if UI changed)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information or examples
      placeholder: Additional context...
    validations:
      required: false
