"""Add adjudication fields

Revision ID: 828ecdd9302d
Revises: 5d9fe59097a3
Create Date: 2025-12-02 19:15:04.409342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828ecdd9302d'
down_revision: Union[str, Sequence[str], None] = '5d9fe59097a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('adjudication_status', sa.String(), nullable=True))
    op.add_column('analysis_results', sa.Column('decision', sa.String(), nullable=True))
    op.add_column('analysis_results', sa.Column('reviewer_notes', sa.String(), nullable=True))
    op.add_column('analysis_results', sa.Column('reviewer_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'analysis_results', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.drop_column('analysis_results', 'reviewer_id')
    op.drop_column('analysis_results', 'reviewer_notes')
    op.drop_column('analysis_results', 'decision')
    op.drop_column('analysis_results', 'adjudication_status')
    # ### end Alembic commands ###
