"""Add adjudication fields

Revision ID: 828ecdd9302d
Revises: 5d9fe59097a3
Create Date: 2025-12-02 19:15:04.409342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828ecdd9302d'
down_revision: Union[str, Sequence[str], None] = '5d9fe59097a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjudication_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('decision', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_notes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reviewer_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_analysis_results_reviewer_id', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_analysis_results_reviewer_id', type_='foreignkey')
        batch_op.drop_column('reviewer_id')
        batch_op.drop_column('reviewer_notes')
        batch_op.drop_column('decision')
        batch_op.drop_column('adjudication_status')
    # ### end Alembic commands ###
