"""add_evidence_models

Revision ID: c708e8d6f85d
Revises: ca8819f168df
Create Date: 2025-12-06 14:58:07.773795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c708e8d6f85d'
down_revision: Union[str, Sequence[str], None] = 'ca8819f168df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DOCUMENT', 'CHAT', 'VIDEO', 'PHOTO', name='evidencetype'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Numeric(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('message_count', sa.Numeric(), nullable=True),
    sa.Column('participant_count', sa.Numeric(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.JSON(), nullable=True),
    sa.Column('network_graph', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_count', sa.Numeric(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('extracted_tables', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('thumbnails', sa.JSON(), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('annotation_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id_1', sa.Uuid(), nullable=False),
    sa.Column('evidence_id_2', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id_1'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['evidence_id_2'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('detected_text', sa.JSON(), nullable=True),
    sa.Column('gps_location', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('duration', sa.Numeric(), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('fps', sa.Numeric(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('transcript_confidence', sa.Numeric(), nullable=True),
    sa.Column('thumbnails', sa.JSON(), nullable=True),
    sa.Column('scenes', sa.JSON(), nullable=True),
    sa.Column('detected_faces', sa.JSON(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('key_moments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('photos')
    op.drop_table('evidence_links')
    op.drop_table('evidence_annotations')
    op.drop_table('documents')
    op.drop_table('chats')
    op.drop_table('evidence')
    # ### end Alembic commands ###
