"""change_transaction_amount_to_numeric

Revision ID: ca8819f168df
Revises: f844a6d9cc61
Create Date: 2025-12-04 16:02:32.364726

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ca8819f168df'
down_revision: Union[str, Sequence[str], None] = 'f844a6d9cc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
