"""Change Transaction.amount to Numeric

Revision ID: f844a6d9cc61
Revises: 337b92c0ede9
Create Date: 2025-12-04 21:34:32.375141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f844a6d9cc61'
down_revision: Union[str, Sequence[str], None] = '337b92c0ede9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                type_=sa.Numeric(precision=10, scale=2),
                existing_nullable=False)
        batch_op.alter_column('date',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=False)
        batch_op.alter_column('created_at',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=True,
                existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
                existing_type=postgresql.TIMESTAMP(timezone=True),
                type_=sa.DateTime(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
                existing_type=sa.DateTime(),
                type_=postgresql.TIMESTAMP(timezone=True),
                existing_nullable=True)
        batch_op.alter_column('created_at',
                existing_type=sa.DateTime(),
                type_=postgresql.TIMESTAMP(timezone=True),
                existing_nullable=True,
                existing_server_default=sa.text('now()'))
        batch_op.alter_column('date',
                existing_type=sa.DateTime(),
                type_=postgresql.TIMESTAMP(timezone=True),
                existing_nullable=False)
        batch_op.alter_column('amount',
                existing_type=sa.Numeric(precision=10, scale=2),
                type_=sa.DOUBLE_PRECISION(precision=53),
                existing_nullable=False)
    # ### end Alembic commands ###
