from pydantic import BaseModel, Field, ConfigDict
from typing import Dict, Any, Optional, List

class DomainEventBase(BaseModel):
    aggregateId: str
    aggregateType: str
    eventType: str
    timestamp: float
    nodeId: str
    clock: int
    version: int
    data: Dict[str, Any]
    correlationId: Optional[str] = None
    causationId: Optional[str] = None
    checksum: str

class DomainEventCreate(DomainEventBase):
    id: str # ID is generated by client

class DomainEvent(DomainEventBase):
    id: str

    model_config = ConfigDict(from_attributes=True)

class SyncRequest(BaseModel):
    events: List[DomainEvent]

class SyncResponse(BaseModel):
    synced: List[str] # IDs of events successfully synced
    failed: List[str] # IDs of events failed
    conflicts: List[DomainEvent] # Remote events causing conflicts
